name: throttle-io-stream
version: '0.2.0.1'
synopsis: Throttler between arbitrary IO producer and consumer functions
description: This packages provides functionality for throttling IO
             using general IO callbacks. The throttling depends on a
             provided configuration. The supported throttling modes
             are producer throttling, consumer throttling or producer
             & consumer throttling.
category: Concurrency
author: Moritz Schulte
maintainer: mtesseract@silverratio.net
copyright: (c) 2017 Moritz Schulte
license: BSD3
github: mtesseract/throttle-io-stream
extra-source-files:
- README.md
ghc-options:
- -Wall
- -fno-warn-type-defaults
dependencies:
- base >=4.7 && <5
- stm
- async
- stm-chans
- clock
library:
  source-dirs: src
  exposed-modules:
  - Control.Concurrent.Throttle
tests:
  throttle-io-stream-test:
    main: Simple.hs
    source-dirs: tests
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -fno-warn-type-defaults
    dependencies:
    - base
    - throttle-io-stream
    - HUnit
    - test-framework
    - test-framework-hunit
    - say
    - text
    - bytestring
    - async
